### ISSUE TITLE
Lnk doesn't work anymore

### ISSUE THREAD

**Issue by partouf** [andreasfertig/cppinsights-web#21]
Hi, the link option via compiler explorer and via the cppinsights website doesn't work anymore.
Probably to do with your latest commits, I'm guessing?

There also seems to be a clientside javascript error. (cookie.min.js:1 Uncaught ReferenceError: module is not defined
    at cookie.min.js:1) (and I did disable cache this time)

**Comment by andreasfertig** [comment]
Urg, this time my cache fooled me. Thanks for reporting. I do a rollback and provide a real fix later.
