### ISSUE TITLE
Possibility of running the cppinsights-web application without docker

### ISSUE THREAD

**Issue by AmeyaVS** [andreasfertig/cppinsights-web#30]
Is it possible to execute the cppinsights-web application in local workspace without using Docker?

I have a local installation of the cppinsight binary built, installed, and added to the PATH environment variable on my shell.

**Comment by andreasfertig** [comment]
Hello @AmeyaVS,

if you are willing to patch `__init__.py` a little then yes.

Have a look [here](https://github.com/andreasfertig/cppinsights-web/blob/84d2dfdf0802b95e80e175d04cb5408613275b98/app/__init__.py#L50):

```
cmd = [ 'sudo', '-u', 'pfes', 'docker', 'run', '--net=none' ]
cmd.extend(fileParam)
cmd.extend(['--rm', '-i', 'insights-test'])
```

replace the there lines it with something like this:
```
cmd = ['insights', fileName]
```

This should to the job.


Andreas

**Comment by AmeyaVS** [comment]
Hello @andreasfertig ,

This modifications works.
Probably It would be better if we can pass it as some command line arguments.

I will look into it later, and probably send you a pull request.

For now, I am closing the issue.

Thank you once again.

Regards,
Ameya Vikram Singh
