### ISSUE TITLE
logo.svg displays incorrectly on machines without "Bitstream Vera Sans" font installed

### ISSUE THREAD

**Issue by apmorton** [andreasfertig/cppinsights-web#45]
Your SVG contains a text element instead of pre-rendered paths for the plus signs:
https://github.com/andreasfertig/cppinsights-web/blob/master/app/static/img/logo.svg?short_path=889ab87#L5

This is what it renders as on my machine, which does not have the correct font installed.
![image](https://user-images.githubusercontent.com/63636/78645273-46153580-7885-11ea-8582-c16dccee2405.png)

Here is an SVG which renders correctly (as compared to the old png logo and favicon.ico):
https://github.com/mattgodbolt/compiler-explorer/blob/master/views/resources/cppinsights.svg

**Comment by andreasfertig** [comment]
Hello @apmorton,

thanks for pointing this out. I missed that while adding the SVG. A font-free version is on its way.

Andreas
