### ISSUE TITLE
"true" and "false" are unreadable when dark theme is enabled.

### ISSUE THREAD

**Issue by d44m1n** [andreasfertig/cppinsights-web#48]
Hi, I would suggest to change current color from `#219` to something like `#65adea`.

![image](https://user-images.githubusercontent.com/11327470/88949772-f6bf9e80-d293-11ea-8b34-bab176c93bed.png)

![image](https://user-images.githubusercontent.com/11327470/88949715-e6a7bf00-d293-11ea-99d4-1c42799d0303.png)

**Comment by andreasfertig** [comment]
Hello @d44m1n,

thanks that slipped under my radar.

Andreas
