### ISSUE TITLE
Right-scrolling in the Source/Insight tabs overlap the line numbers

### ISSUE THREAD

**Issue by i3abghany** [andreasfertig/cppinsights-web#54]
Before scrolling:

![image](https://user-images.githubusercontent.com/19896973/130316230-6fab9e03-dfd9-407d-bf3e-f396b42fee3d.png)

After scrolling:

![image](https://user-images.githubusercontent.com/19896973/130316233-93e56077-9ef1-4ae5-a0a4-a80e4a9dedcd.png)

This happens in both Source and Insight tabs.

**Comment by andreasfertig** [comment]
Hello @i3abghany,

thank you for reporting this and sorry for the delay. A fix is on its way.

Andreas
